import { useEffect, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

// High-poly Metalab logo loaded from a pre-baked GLB. Replaces the
// runtime ExtrudeGeometry (4 arms, ~500 verts) with the offline-built
// mesh (~21k verts, 33k tris, all four arms welded into one geometry,
// plane-projected UVs ready for tiling PBR textures + displacement).
//
// Generated by scripts/build-logo-glb.mjs.

useGLTF.preload('/models/metalab-logo.glb')

export default function Rock3D({
  material,
  position = [0, 0, 0],
  scale = 1,
  rotation = [0, 0, 0],
  onPointerOver,
  onPointerOut,
}) {
  const { scene } = useGLTF('/models/metalab-logo.glb')

  // Pull the merged mesh from the loaded scene so we can attach our
  // own material instead of whatever the GLB shipped with.
  const geometry = useMemo(() => {
    let g = null
    scene.traverse((o) => { if (o.isMesh && !g) g = o.geometry })
    return g
  }, [scene])

  // Make sure the displacement map renders correctly: smooth shading,
  // recompute normals after any tessellation that happened upstream.
  useEffect(() => {
    if (!geometry) return
    geometry.computeVertexNormals()
  }, [geometry])

  if (!geometry || !material) return null

  return (
    <mesh
      geometry={geometry}
      material={material}
      position={position}
      scale={scale}
      rotation={rotation}
      castShadow
      receiveShadow
      onPointerOver={onPointerOver}
      onPointerOut={onPointerOut}
    />
  )
}
