// Progetto Happiness — Episode & Location Data
// Source: progettohappiness.com + YouTube @ProgettoHappiness

export const PROJECT_INFO = {
  name: 'Progetto Happiness',
  founder: 'Giuseppe Bertuccio D\'Angelo',
  founded: 2019,
  description: 'Un viaggio alla ricerca delle infinite sfumature della felicità attraverso culture, popoli e filosofie di vita.',
  stats: {
    subscribers: '2.7M',
    followers: '503K',
    episodes: '900+',
    countries: '50+',
  },
};

// Each episode with geocoordinates for globe placement
export const episodes = [
  {
    id: 1,
    title: 'BDSM: dentro il mondo segreto del piacere',
    description: 'Cosa spinge un manager di successo a pagare per farsi umiliare? Un viaggio nel mondo sommerso del BDSM a San Francisco.',
    location: 'San Francisco, USA',
    country: 'USA',
    lat: 37.7749,
    lng: -122.4194,
    youtubeSearch: 'Progetto Happiness BDSM San Francisco',
    views: '4.2M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2026/03/SlaveMen.jpg',
  },
  {
    id: 2,
    title: 'I soldi fanno la felicità?',
    description: 'Paracelsus Recovery a Zurigo è la clinica di salute mentale più esclusiva del pianeta. I soldi possono davvero comprare la felicità?',
    location: 'Zurigo, Svizzera',
    country: 'Svizzera',
    lat: 47.3769,
    lng: 8.5417,
    youtubeSearch: 'Progetto Happiness soldi felicità Zurigo',
    views: '2.8M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2026/02/paracelsius-recovery-cover.jpg',
  },
  {
    id: 3,
    title: 'Riserva di Pine Ridge',
    description: 'La felicità nel luogo più povero degli Stati Uniti. La riserva indiana di Pine Ridge, tra i Lakota.',
    location: 'South Dakota, USA',
    country: 'USA',
    lat: 43.0,
    lng: -102.5,
    youtubeSearch: 'Progetto Happiness Pine Ridge Lakota',
    views: '3.1M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2026/02/Pine-Ridge-2.jpg',
  },
  {
    id: 4,
    title: 'Gold\'s Gym Venice',
    description: 'La Mecca del bodybuilding dove si è allenato Arnold Schwarzenegger. Cosa significa inseguire il corpo perfetto?',
    location: 'Venice, California',
    country: 'USA',
    lat: 33.985,
    lng: -118.472,
    youtubeSearch: 'Progetto Happiness Gold Gym Venice',
    views: '1.9M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2026/02/Bodybuilders.jpg',
  },
  {
    id: 5,
    title: 'Preppers: pronti alla fine del mondo',
    description: 'Persone che si preparano alla fine del mondo. Bunker, scorte e sopravvivenza negli Stati Uniti.',
    location: 'USA',
    country: 'USA',
    lat: 39.8283,
    lng: -98.5795,
    youtubeSearch: 'Progetto Happiness Preppers bunker',
    views: '2.5M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2026/01/Preppers-Cover.jpg',
  },
  {
    id: 6,
    title: 'La vita degli ultimi cowboy',
    description: 'La vita degli ultimi cowboy nel Far West americano. Montana, cavalli e libertà.',
    location: 'Montana, USA',
    country: 'USA',
    lat: 46.8797,
    lng: -110.3626,
    youtubeSearch: 'Progetto Happiness cowboy Montana',
    views: '2.1M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2026/01/Cowboy-Cover.jpg',
  },
  {
    id: 7,
    title: 'Orania: la città più razzista al mondo',
    description: 'La città più razzista al mondo. Un enclave afrikaner nel cuore del Sudafrica.',
    location: 'Orania, Sudafrica',
    country: 'Sudafrica',
    lat: -29.818,
    lng: 24.615,
    youtubeSearch: 'Progetto Happiness Orania Sudafrica',
    views: '5.1M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/11/Orania.jpg',
  },
  {
    id: 8,
    title: 'Cape Town: vivere o morire',
    description: 'La città più pericolosa al mondo. Cape Town tra bellezza estrema e violenza quotidiana.',
    location: 'Cape Town, Sudafrica',
    country: 'Sudafrica',
    lat: -33.9249,
    lng: 18.4241,
    youtubeSearch: 'Progetto Happiness Cape Town pericolosa',
    views: '3.7M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/11/Khaytelitsha.jpg',
  },
  {
    id: 9,
    title: 'Black Mambas',
    description: 'Sopravvivere disarmati tra gli animali feroci. Le Black Mambas, ranger anti-bracconaggio nel Kruger National Park.',
    location: 'Kruger Park, Sudafrica',
    country: 'Sudafrica',
    lat: -23.9884,
    lng: 31.5547,
    youtubeSearch: 'Progetto Happiness Black Mambas Kruger',
    views: '1.8M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/11/sopravvivere-animali-africa.jpg',
  },
  {
    id: 10,
    title: 'Come cambiare la vita a 300 bambini',
    description: 'Costruire una scuola in Zimbabwe. Il Progetto Scuola che ha cambiato la vita a 300 bambini.',
    location: 'Kapale, Zimbabwe',
    country: 'Zimbabwe',
    lat: -19.0,
    lng: 29.0,
    youtubeSearch: 'Progetto Happiness scuola Zimbabwe',
    views: '2.3M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/09/THUMB-ZIMBABWE-3.jpg',
  },
  {
    id: 11,
    title: '48h con i Monaci Buddhisti',
    description: 'I monaci che custodiscono il segreto della felicità. 48 ore nel cuore spirituale di Luang Prabang.',
    location: 'Luang Prabang, Laos',
    country: 'Laos',
    lat: 19.8856,
    lng: 102.1347,
    youtubeSearch: 'Progetto Happiness monaci buddhisti Laos',
    views: '4.5M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/09/THUMB-2.jpg',
  },
  {
    id: 12,
    title: 'Muay Thai: la lotta più dura al mondo',
    description: 'La Muay Thai in Tailandia. Bambini che combattono per sopravvivere.',
    location: 'Tailandia',
    country: 'Tailandia',
    lat: 13.7563,
    lng: 100.5018,
    youtubeSearch: 'Progetto Happiness Muay Thai Tailandia',
    views: '3.2M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/09/MuayThai1.jpg',
  },
  {
    id: 13,
    title: 'Gli uomini elefante',
    description: 'La tribù dei Mahout che vive con gli elefanti. Un legame millenario in Tailandia.',
    location: 'Tailandia',
    country: 'Tailandia',
    lat: 18.7883,
    lng: 98.9853,
    youtubeSearch: 'Progetto Happiness Mahout elefanti Tailandia',
    views: '2.0M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/08/THUMB-ELEPHANTS-3.jpg',
  },
  {
    id: 14,
    title: 'Laamb: i gladiatori d\'Africa',
    description: 'Diventare il più grande gladiatore d\'Africa. La lotta Laamb a Dakar, Senegal.',
    location: 'Dakar, Senegal',
    country: 'Senegal',
    lat: 14.7167,
    lng: -17.4677,
    youtubeSearch: 'Progetto Happiness Laamb Dakar Senegal',
    views: '2.6M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/07/Laamb.jpg',
  },
  {
    id: 15,
    title: 'Miniere illegali di smeraldi',
    description: 'Dentro le miniere illegali di smeraldi in Colombia. Rischio, povertà e speranza.',
    location: 'Boyacá, Colombia',
    country: 'Colombia',
    lat: 5.4545,
    lng: -73.362,
    youtubeSearch: 'Progetto Happiness miniere smeraldi Colombia',
    views: '3.8M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/07/miniere-smeraldi-colombia.jpg',
  },
  {
    id: 16,
    title: 'Il più grande cimitero elettronico',
    description: 'Dentro il più grande cimitero elettronico del pianeta. Agbogbloshie, Ghana.',
    location: 'Agbogbloshie, Ghana',
    country: 'Ghana',
    lat: 5.5527,
    lng: -0.2342,
    youtubeSearch: 'Progetto Happiness Agbogbloshie Ghana',
    views: '2.9M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/07/discarica-Ghana.jpg',
  },
  {
    id: 17,
    title: 'Le tribù urbane di New York',
    description: 'Chi sono i veri americani? Le tribù urbane di New York City.',
    location: 'New York, USA',
    country: 'USA',
    lat: 40.7128,
    lng: -74.006,
    youtubeSearch: 'Progetto Happiness tribù urbane New York',
    views: '1.7M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/07/urban-tribes.jpg',
  },
  {
    id: 18,
    title: 'Diventare un uomo invisibile',
    description: 'La vita di un senzatetto a New York. Diventare un uomo invisibile nella città che non dorme mai.',
    location: 'New York, USA',
    country: 'USA',
    lat: 40.7580,
    lng: -73.9855,
    youtubeSearch: 'Progetto Happiness senzatetto New York',
    views: '3.4M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/07/Homeless.jpg',
  },
  {
    id: 19,
    title: 'Una notte con i banditi di Bogotá',
    description: 'Una notte con i banditi di Bogotá. Il lato oscuro della capitale colombiana.',
    location: 'Bogotá, Colombia',
    country: 'Colombia',
    lat: 4.711,
    lng: -74.0721,
    youtubeSearch: 'Progetto Happiness banditi Bogotá',
    views: '4.1M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/05/Banditi-Bogota.jpg',
  },
  {
    id: 20,
    title: 'Il popolo che salverà il mondo',
    description: 'La tribù Kogui nella selva colombiana. Il popolo che crede di poter salvare il mondo.',
    location: 'Sierra Nevada, Colombia',
    country: 'Colombia',
    lat: 10.8,
    lng: -73.7,
    youtubeSearch: 'Progetto Happiness Kogui Colombia',
    views: '2.7M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/04/Kogui-Tribe-1.jpg',
  },
  {
    id: 21,
    title: 'L\'isola più affollata del mondo',
    description: 'Come sopravvivere in 1.000 su un\'isola grande quanto un campo da calcio? Santa Cruz del Islote.',
    location: 'Santa Cruz del Islote, Colombia',
    country: 'Colombia',
    lat: 9.685,
    lng: -75.883,
    youtubeSearch: 'Progetto Happiness Santa Cruz Islote',
    views: '5.3M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/04/Isola-di-Santa-Cruz.jpg',
  },
  {
    id: 22,
    title: 'Rastafarianesimo in Giamaica',
    description: 'La religione che venera la pianta della conoscenza. Il rastafarianesimo in Giamaica.',
    location: 'Giamaica',
    country: 'Giamaica',
    lat: 18.1096,
    lng: -77.2975,
    youtubeSearch: 'Progetto Happiness Rastafarianesimo Giamaica',
    views: '2.2M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/03/Rastamen1.jpg',
  },
  {
    id: 23,
    title: 'Guerrieri Kara: l\'arte della sopravvivenza',
    description: 'L\'arte della sopravvivenza nella Valle dell\'Omo, Etiopia. I guerrieri della tribù Kara.',
    location: 'Valle dell\'Omo, Etiopia',
    country: 'Etiopia',
    lat: 5.5,
    lng: 36.0,
    youtubeSearch: 'Progetto Happiness guerrieri Kara Etiopia',
    views: '1.5M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/03/Kara.jpg',
  },
  {
    id: 24,
    title: 'Il rito delle donne frustate',
    description: 'Il rito delle donne frustate nella tribù degli Hamer. Valle dell\'Omo, Etiopia.',
    location: 'Valle dell\'Omo, Etiopia',
    country: 'Etiopia',
    lat: 5.3,
    lng: 36.5,
    youtubeSearch: 'Progetto Happiness Hamer Etiopia',
    views: '2.4M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/03/Hamer.jpg',
  },
  {
    id: 49,
    title: 'Il rituale del Dimi',
    description: 'Il passaggio da bambina a donna nella tribù dei Dassanech. Un rito millenario nella Valle dell\'Omo.',
    location: 'Valle dell\'Omo, Etiopia',
    country: 'Etiopia',
    lat: 4.8,
    lng: 36.3,
    youtubeSearch: 'Progetto Happiness Dimi Dassanech Etiopia',
    views: '1.6M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/03/Dimi.jpg',
  },
  {
    id: 50,
    title: 'La cerimonia del sangue dei Suri',
    description: 'La cerimonia del sangue con la tribù dei Suri. Un rito ancestrale nella Valle dell\'Omo, Etiopia.',
    location: 'Valle dell\'Omo, Etiopia',
    country: 'Etiopia',
    lat: 5.8,
    lng: 35.5,
    youtubeSearch: 'Progetto Happiness Suri cerimonia sangue Etiopia',
    views: '2.0M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/12/Suri-Tribe-Thumbnail.jpg',
  },
  {
    id: 25,
    title: 'Gli ultimi uomini della pietra',
    description: 'Sopravvivere nella savana con gli Hadzabe. Gli ultimi cacciatori-raccoglitori della Tanzania.',
    location: 'Tanzania',
    country: 'Tanzania',
    lat: -3.3869,
    lng: 36.6,
    youtubeSearch: 'Progetto Happiness Hadzabe Tanzania',
    views: '3.6M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/03/Hadzabe-Primitive-Hunters.jpg',
  },
  {
    id: 26,
    title: 'La tribù della felicità',
    description: 'I Chewa: la tribù della felicità in Malawi. Un popolo che celebra la vita attraverso la danza.',
    location: 'Malawi',
    country: 'Malawi',
    lat: -13.2543,
    lng: 34.3015,
    youtubeSearch: 'Progetto Happiness Chewa Malawi',
    views: '1.9M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/12/thumb1.jpg',
  },
  {
    id: 27,
    title: 'L\'isola segreta degli albini',
    description: 'L\'isola segreta degli albini africani nel Lago Vittoria, Tanzania.',
    location: 'Lago Vittoria, Tanzania',
    country: 'Tanzania',
    lat: -1.0,
    lng: 33.0,
    youtubeSearch: 'Progetto Happiness albini Tanzania',
    views: '2.8M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/11/Albinos-Tanzania.jpeg',
  },
  {
    id: 28,
    title: 'I cacciatori con le aquile',
    description: 'I cacciatori con le aquile della Mongolia. Una tradizione millenaria nelle steppe gelate.',
    location: 'Mongolia',
    country: 'Mongolia',
    lat: 48.0,
    lng: 89.0,
    youtubeSearch: 'Progetto Happiness cacciatori aquile Mongolia',
    views: '3.3M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/11/Thumb-3.jpg',
  },
  {
    id: 29,
    title: 'Il lavoro più duro al mondo',
    description: 'Gli uomini fogna dell\'India. Il lavoro più duro e pericoloso al mondo.',
    location: 'India',
    country: 'India',
    lat: 28.6139,
    lng: 77.209,
    youtubeSearch: 'Progetto Happiness uomini fogna India',
    views: '4.7M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/10/Manual-thumb-1.jpg',
  },
  {
    id: 30,
    title: 'L\'ultimo matriarcato contro i Talebani',
    description: 'I Kalash: l\'ultimo matriarcato che combatte i Talebani nel cuore del Pakistan.',
    location: 'Chitral, Pakistan',
    country: 'Pakistan',
    lat: 35.7,
    lng: 71.5,
    youtubeSearch: 'Progetto Happiness Kalash Pakistan',
    views: '3.9M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/10/Kalash-thumb-1.jpg',
  },
  {
    id: 31,
    title: 'I bambini minatori della Sierra Leone',
    description: 'I diamanti sporchi. I bambini minatori delle miniere di diamanti della Sierra Leone.',
    location: 'Sierra Leone',
    country: 'Sierra Leone',
    lat: 8.4606,
    lng: -11.7799,
    youtubeSearch: 'Progetto Happiness diamanti Sierra Leone',
    views: '2.1M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/09/Blood-Diamonds-Cover-YouTube.jpg',
  },
  {
    id: 32,
    title: 'Le strade più pericolose al mondo',
    description: 'I camionisti del Pakistan sulle strade più pericolose al mondo. Karakoram Highway.',
    location: 'Karakoram, Pakistan',
    country: 'Pakistan',
    lat: 36.3,
    lng: 75.5,
    youtubeSearch: 'Progetto Happiness camionisti Pakistan Karakoram',
    views: '2.5M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/09/ThumB-4.jpg',
  },
  {
    id: 33,
    title: 'Monte Athos: dove le donne non entrano',
    description: 'L\'unica nazione dove le donne non possono entrare. Monte Athos, Grecia.',
    location: 'Monte Athos, Grecia',
    country: 'Grecia',
    lat: 40.1564,
    lng: 24.3284,
    youtubeSearch: 'Progetto Happiness Monte Athos Grecia',
    views: '4.0M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/09/Athos.jpg',
  },
  {
    id: 34,
    title: 'Monaci Shaolin',
    description: 'Dentro il tempio dei monaci Shaolin. Disciplina, kung fu e spiritualità in Cina.',
    location: 'Henan, Cina',
    country: 'Cina',
    lat: 34.5,
    lng: 112.9,
    youtubeSearch: 'Progetto Happiness Shaolin Cina',
    views: '3.5M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/07/KF8b.jpg',
  },
  {
    id: 35,
    title: 'La prima comunità trans musulmana',
    description: 'La prima comunità trans musulmana in Bangladesh. Dhaka, tra fede e identità.',
    location: 'Dhaka, Bangladesh',
    country: 'Bangladesh',
    lat: 23.8103,
    lng: 90.4125,
    youtubeSearch: 'Progetto Happiness trans musulmana Bangladesh',
    views: '2.6M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/06/Thumb2.jpg',
  },
  {
    id: 36,
    title: 'Fast Fashion: i bambini operai',
    description: 'La storia dei bambini operai nel Fast Fashion. Bangladesh, il prezzo dei vestiti che indossiamo.',
    location: 'Bangladesh',
    country: 'Bangladesh',
    lat: 23.685,
    lng: 90.356,
    youtubeSearch: 'Progetto Happiness fast fashion Bangladesh',
    views: '3.0M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/06/ff2.jpg',
  },
  {
    id: 37,
    title: 'La tribù che sopravvive a -50°',
    description: 'Gli uomini renna della Mongolia. La tribù Tsaatan che sopravvive a -50° tra orsi e lupi.',
    location: 'Mongolia',
    country: 'Mongolia',
    lat: 51.1,
    lng: 99.0,
    youtubeSearch: 'Progetto Happiness uomini renna Mongolia Tsaatan',
    views: '4.3M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/05/Renne2.jpg',
  },
  {
    id: 38,
    title: 'Terre sacre degli sciamani',
    description: 'Viaggio alla scoperta delle terre sacre degli sciamani in Mongolia.',
    location: 'Mongolia',
    country: 'Mongolia',
    lat: 47.9,
    lng: 106.9,
    youtubeSearch: 'Progetto Happiness sciamani Mongolia',
    views: '2.4M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/05/Thumb-6.jpg',
  },
  {
    id: 39,
    title: 'La città segreta nel cimitero',
    description: 'Vivere nelle tombe. La città segreta nel cimitero di Manila, Filippine.',
    location: 'Manila, Filippine',
    country: 'Filippine',
    lat: 14.5995,
    lng: 120.9842,
    youtubeSearch: 'Progetto Happiness cimitero Manila Filippine',
    views: '3.7M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/05/Thumb-1.jpg',
  },
  {
    id: 40,
    title: 'La prigione autogestita dalle gang',
    description: 'Dentro la prigione autogestita dalle gang a Manila.',
    location: 'Manila, Filippine',
    country: 'Filippine',
    lat: 14.58,
    lng: 121.0,
    youtubeSearch: 'Progetto Happiness prigione gang Manila',
    views: '4.8M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/04/Thumb4.jpg',
  },
  {
    id: 41,
    title: 'Uomini pesce Badjao',
    description: 'Mutati geneticamente per sopravvivere in mare. I Badjao delle Filippine.',
    location: 'Filippine',
    country: 'Filippine',
    lat: 6.0,
    lng: 121.0,
    youtubeSearch: 'Progetto Happiness Badjao Filippine',
    views: '2.9M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/04/3.jpg',
  },
  {
    id: 42,
    title: 'Cucinare la spazzatura per sopravvivere',
    description: 'Pag Pag: cucinare la spazzatura per sopravvivere a Manila.',
    location: 'Manila, Filippine',
    country: 'Filippine',
    lat: 14.62,
    lng: 120.97,
    youtubeSearch: 'Progetto Happiness Pag Pag Manila',
    views: '3.1M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/04/PagPag1.jpg',
  },
  {
    id: 43,
    title: 'Canoni di bellezza in Mauritania',
    description: 'Le donne obese della Mauritania. Canoni estetici della bellezza femminile.',
    location: 'Mauritania',
    country: 'Mauritania',
    lat: 18.0735,
    lng: -15.9582,
    youtubeSearch: 'Progetto Happiness donne obese Mauritania',
    views: '2.3M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/03/Fat-Women.jpg',
  },
  {
    id: 44,
    title: 'La febbre dell\'oro africano',
    description: 'La febbre dell\'oro nella Mauritania. Minatori alla ricerca della fortuna nel deserto.',
    location: 'Mauritania',
    country: 'Mauritania',
    lat: 20.0,
    lng: -12.0,
    youtubeSearch: 'Progetto Happiness febbre oro Mauritania',
    views: '1.8M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/03/Thumb1.jpg',
  },
  {
    id: 45,
    title: 'Il villaggio senza occhi',
    description: 'Dali Koumbè: il villaggio della tribù senza occhi nel deserto del Sahara.',
    location: 'Sahara, Mauritania',
    country: 'Mauritania',
    lat: 17.0,
    lng: -10.0,
    youtubeSearch: 'Progetto Happiness villaggio senza occhi Mauritania',
    views: '3.5M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/02/Thumb-4.jpg',
  },
  {
    id: 46,
    title: 'Il treno del ferro',
    description: 'Viaggio clandestino sul treno del ferro in Mauritania. Il treno più lungo e pericoloso al mondo.',
    location: 'Mauritania',
    country: 'Mauritania',
    lat: 21.3,
    lng: -13.0,
    youtubeSearch: 'Progetto Happiness treno ferro Mauritania',
    views: '5.7M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/01/TrenoScrittaSotto.jpg',
  },
  {
    id: 47,
    title: 'Una fidanzata in affitto a Tokyo',
    description: 'Una fidanzata in affitto a Tokyo. Il business della solitudine in Giappone.',
    location: 'Tokyo, Giappone',
    country: 'Giappone',
    lat: 35.6762,
    lng: 139.6503,
    youtubeSearch: 'Progetto Happiness fidanzata affitto Tokyo',
    views: '6.2M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/01/Thumb-2.jpg',
  },
  {
    id: 48,
    title: 'Ocean Viking: salvataggio nel Mediterraneo',
    description: 'Il primo content creator a bordo della Ocean Viking. Missione di salvataggio nel Mar Mediterraneo.',
    location: 'Mar Mediterraneo',
    country: 'Mediterraneo',
    lat: 35.0,
    lng: 15.0,
    youtubeSearch: 'Progetto Happiness Ocean Viking Mediterraneo',
    views: '1.6M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/04/Thumbnail-Ocean-VIking.jpg',
  },
  {
    id: 51,
    title: 'Il regno dei nani: dentro il parco giochi più controverso del mondo',
    description: 'In Cina esiste un luogo tanto magico quanto controverso: il Regno dei Nani! Questo parco giochi è unico nel suo genere, abitato e gestito esclusivamente da persone affette da nanismo.',
    location: 'Kunming, Cina',
    country: 'Cina',
    lat: 25.0389,
    lng: 102.7183,
    youtubeSearch: 'Progetto Happiness regno dei nani Cina',
    views: '',
    date: '2024',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/07/Dwarves-thumb-12.jpg',
  },
  {
    id: 52,
    title: 'Una notte con l\'ultima Geisha di Tokyo',
    description: 'C\'è sempre stato un alone di mistero e ambiguità sulla figura della Geisha. In occidente viene troppo spesso confusa con una sorta di escort, mentre in realtà in Giappone è considerata quasi una divinità.',
    location: 'Tokyo, Giappone',
    country: 'Giappone',
    lat: 35.7148,
    lng: 139.7967,
    youtubeSearch: 'Progetto Happiness ultima Geisha Tokyo',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/12/Thumb1.jpg',
  },
  {
    id: 53,
    title: 'Monaci giapponesi dai poteri soprannaturali',
    description: 'Si crede che la saggezza millenaria dello Shugendo custodisca tutte le risposte che l\'uomo ricerca da sempre. Questa religione unisce pratiche buddhiste, scintoiste e taoiste con la magia esoterica.',
    location: 'Giappone',
    country: 'Giappone',
    lat: 38.7,
    lng: 139.98,
    youtubeSearch: 'Progetto Happiness monaci Shugendo Giappone',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/12/ShugendoNew.jpg',
  },
  {
    id: 54,
    title: 'L\'arte del sushi a Tokyo',
    description: 'Se vi chiedessi: qual è il cibo più famoso al mondo (a parte la pizza) cosa rispondereste? Non c\'è alcun dubbio: il sushi!',
    location: 'Tokyo, Giappone',
    country: 'Giappone',
    lat: 35.6762,
    lng: 139.6503,
    youtubeSearch: 'Progetto Happiness arte sushi Tokyo',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/12/Sushi-thumb-1.jpg',
  },
  {
    id: 55,
    title: 'La via dei samurai: alla scoperta del Giappone autentico',
    description: 'In Giappone esiste un cammino che, se percorso per intero, ti porta indietro nel tempo, sino all\'epoca dei Samurai! Questo cammino si chiama: la via del Nakasendo.',
    location: 'Nakasendo, Giappone',
    country: 'Giappone',
    lat: 35.84,
    lng: 137.56,
    youtubeSearch: 'Progetto Happiness via samurai Nakasendo Giappone',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/11/Thumb-2.jpg',
  },
  {
    id: 56,
    title: 'Diventare un calciatore professionista: dalla favela alla Serie A',
    description: 'Il calcio è solo un gioco? In Brasile, e più nello specifico nelle favelas di Rio de Janeiro, il calcio è una questione serissima!',
    location: 'Rio de Janeiro, Brasile',
    country: 'Brasile',
    lat: -22.9068,
    lng: -43.1729,
    youtubeSearch: 'Progetto Happiness calciatore favela Serie A Brasile',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/10/Thumb-5.jpg',
  },
  {
    id: 57,
    title: 'Dentro la favela di San Paolo',
    description: 'In Brasile, la favela di Heliopolis è considerata la seconda favela più grande dell\'America Latina, con circa 200.000 abitanti. Le vecchie baracche in pochi decenni hanno dato origine a costruzioni in mattoni.',
    location: 'Heliopolis, San Paolo, Brasile',
    country: 'Brasile',
    lat: -23.6,
    lng: -46.6,
    youtubeSearch: 'Progetto Happiness favela Heliopolis San Paolo',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/10/Thumb-1.jpg',
  },
  {
    id: 58,
    title: 'Razzismo ambientale nel cuore del Brasile',
    description: 'Avete mai sentito parlare di razzismo ambientale? È quando tribù, villaggi, o comunità sono esposte a inquinamento, scarichi tossici o sfruttamento delle risorse naturali a causa della loro origine razziale o etnica.',
    location: 'Brasile',
    country: 'Brasile',
    lat: -14.235,
    lng: -51.9253,
    youtubeSearch: 'Progetto Happiness razzismo ambientale Brasile',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/10/Brasile.jpeg',
  },
  {
    id: 59,
    title: 'Il Regno degli Zingari: la città dove comandano i ROM',
    description: 'Vicino a Skopje, la capitale della Macedonia del Nord, si trova una città unica al mondo. Si chiama Shuto Orizari, o anche detta: il Regno dei ROM!',
    location: 'Shuto Orizari, Skopje, Macedonia del Nord',
    country: 'Macedonia del Nord',
    lat: 42.03,
    lng: 21.44,
    youtubeSearch: 'Progetto Happiness regno zingari ROM Skopje',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/09/Thumb-Macedonia-1.jpg',
  },
  {
    id: 60,
    title: 'Albania segreta: tatuatori in bunker antiatomici e spie comuniste',
    description: 'Albania è il paese più bunkerizzato al mondo! I bunker costruiti durante l\'era del regime comunista del dittatore Enver Hoxha hanno segnato la vita del popolo albanese.',
    location: 'Albania',
    country: 'Albania',
    lat: 41.3275,
    lng: 19.8187,
    youtubeSearch: 'Progetto Happiness Albania bunker tatuatori spie',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/07/Thumb-1-Albania.jpg',
  },
  {
    id: 61,
    title: 'L\'ultimo cacciatore di balene delle Azzorre',
    description: 'In mezzo all\'Oceano Atlantico ci sono delle isole soprannominate il giardino segreto dell\'Atlantico: le Azzorre! Un tempo conosciute per essere la casa dei migliori cacciatori di balene al mondo.',
    location: 'Isola di Pico, Azzorre, Portogallo',
    country: 'Portogallo',
    lat: 38.4667,
    lng: -28.3167,
    youtubeSearch: 'Progetto Happiness cacciatore balene Azzorre',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/06/Thumb-3.jpg',
  },
  {
    id: 62,
    title: 'Dentro la baraccopoli più grande dell\'Asia',
    description: 'A Mumbai si trova una baraccopoli unica al mondo, quella di Dharavi, il formicaio umano di Mumbai. A Dharavi vivono circa 2 milioni di persone in un\'area ridottissima.',
    location: 'Dharavi, Mumbai, India',
    country: 'India',
    lat: 19.0438,
    lng: 72.8535,
    youtubeSearch: 'Progetto Happiness Dharavi Mumbai baraccopoli Asia',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/06/Thumb-8.jpg',
  },
  {
    id: 63,
    title: 'I cannibali della città sacra in India',
    description: 'In India c\'è un luogo che viene considerato da millenni la città sacra. Si tratta di Varanasi ed è proprio qui qualsiasi induista desidererebbe morire ed essere cremato.',
    location: 'Varanasi, India',
    country: 'India',
    lat: 25.3176,
    lng: 83.0064,
    youtubeSearch: 'Progetto Happiness cannibali Varanasi India',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/05/Thumb2.jpg',
  },
  {
    id: 64,
    title: 'La Dea vivente del Nepal',
    description: 'In Nepal esiste una tradizione millenaria che venera una dea vivente, una bambina chiamata: Kumari. La prescelta dev\'essere una bambina vergine con 32 tratti estetici specifici.',
    location: 'Kathmandu, Nepal',
    country: 'Nepal',
    lat: 27.7172,
    lng: 85.324,
    youtubeSearch: 'Progetto Happiness Dea vivente Kumari Nepal',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/05/Dea-Bambina.jpg',
  },
  {
    id: 65,
    title: 'Una notte nel quartiere trans di Bangkok',
    description: 'Bangkok è conosciuta in tutto il mondo per il turismo sessuale che ogni anno porta milioni di stranieri nei quartieri a luci rosse come Soi Cowboy e Nana Plaza. L\'attrazione principale sono i Ladyboy.',
    location: 'Bangkok, Tailandia',
    country: 'Tailandia',
    lat: 13.7563,
    lng: 100.5018,
    youtubeSearch: 'Progetto Happiness quartiere trans Bangkok',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/05/bangkok-5.jpg',
  },
  {
    id: 66,
    title: 'Gli Hare Krishna: setta o religione?',
    description: 'Li abbiamo visti tutti almeno una volta. Nelle piazze, nelle stazioni, sui mezzi pubblici.',
    location: 'Vicenza, Italia',
    country: 'Italia',
    lat: 45.5455,
    lng: 11.5354,
    youtubeSearch: 'Progetto Happiness Hare Krishna setta religione',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/04/Thumb6.jpg',
  },
  {
    id: 67,
    title: 'L\'ultimo beduino del deserto del Wadi Rum',
    description: 'In Giordania, nel deserto del Wadi Rum, vivono e resistono ancora 4 famiglie di Beduini: gli ultimi nomadi del deserto! Sono andato per incontrare Mutlaq, uno degli ultimi beduini.',
    location: 'Wadi Rum, Giordania',
    country: 'Giordania',
    lat: 29.5321,
    lng: 35.4111,
    youtubeSearch: 'Progetto Happiness ultimo beduino Wadi Rum Giordania',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/04/Thumb-Giordania.jpg',
  },
  {
    id: 68,
    title: 'Dentro la città fantasma in Palestina',
    description: 'C\'è una città in Palestina che sta scomparendo. Il suo vero nome è Hebron, ma tutti ormai la chiamano ghost town perché la maggior parte delle case e dei negozi è stata abbandonata.',
    location: 'Hebron, Palestina',
    country: 'Palestina',
    lat: 31.5326,
    lng: 35.0998,
    youtubeSearch: 'Progetto Happiness città fantasma Hebron Palestina',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/03/Thumb-1.jpg',
  },
  {
    id: 69,
    title: 'Palestina: vivere separati da un muro',
    description: 'Immaginati di essere cittadino di un paese che non esiste nelle mappe. Immaginati di aprire la finestra di casa tua e vedere davanti a te un muro.',
    location: 'Palestina',
    country: 'Palestina',
    lat: 31.9,
    lng: 35.2,
    youtubeSearch: 'Progetto Happiness Palestina muro separazione',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/03/Thumb-4.jpg',
  },
  {
    id: 70,
    title: 'Ucraina: vivere dentro la guerra - Bucha e Irpin',
    description: 'Vi siete mai chiesti come si vive veramente dentro un paese in guerra? In questo secondo episodio si visitano Bucha e Irpin, città vicino a Kiev pesantemente colpite.',
    location: 'Bucha, Ucraina',
    country: 'Ucraina',
    lat: 50.5474,
    lng: 30.2117,
    youtubeSearch: 'Progetto Happiness Ucraina Bucha Irpin guerra',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/02/Thumbnail-Ucraina-02.jpg',
  },
  {
    id: 71,
    title: 'Ucraina: cosa vuol dire vivere dentro la guerra',
    description: 'Vi siete mai chiesti come si vive veramente dentro un paese in guerra? Ormai è passato un anno dallo scoppio della guerra tra Russia e Ucraina.',
    location: 'Ucraina',
    country: 'Ucraina',
    lat: 50.4501,
    lng: 30.5234,
    youtubeSearch: 'Progetto Happiness Ucraina vivere guerra',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/02/Thumbnail-Ucraina.jpg',
  },
  {
    id: 72,
    title: 'Nella vita di un ebreo ultraortodosso',
    description: 'In questo nuovo reportage vi porto in un viaggio di scoperta della cultura ebraica. In compagnia della sapiente guida di Edo, sono entrato nel mondo della corrente ultra-ortodossa chassidica.',
    location: 'Israele',
    country: 'Israele',
    lat: 31.7683,
    lng: 35.2137,
    youtubeSearch: 'Progetto Happiness ebreo ultraortodosso chassidico',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/02/thumbnail-matrimonio-ultraortodossi.jpg',
  },
  {
    id: 73,
    title: 'La valle del Ketama e il mercato dell\'hashish',
    description: 'In Marocco esiste una valle dalla quale parte il commercio mondiale di hashish: la valle del Ketama! È un business da miliardi di euro.',
    location: 'Ketama, Marocco',
    country: 'Marocco',
    lat: 34.9167,
    lng: -4.5667,
    youtubeSearch: 'Progetto Happiness Ketama hashish Marocco',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/01/Thumbnail-1.jpg',
  },
  {
    id: 74,
    title: 'Il clan delle montagne marocchine',
    description: 'Nel cuore pulsante dell\'Atlas, Giuseppe ha incontrato Ahmed, un pastore marocchino che ha aperto le porte ai primi europei bianchi arrivati nel suo villaggio.',
    location: 'Montagne dell\'Atlas, Marocco',
    country: 'Marocco',
    lat: 31.5,
    lng: -6.5,
    youtubeSearch: 'Progetto Happiness clan montagne Atlas Marocco',
    views: '',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2023/01/Thmb-3.jpg',
  },
  {
    id: 75,
    title: 'La Tribù dei Waorani',
    description: 'Ecuador. Parco Nazionale Yasuní. Uno degli ultimi santuari della biodiversità del Pianeta. Ho trascorso qualche giorno immerso nella vita e nella cultura dei Waorani.',
    location: 'Parco Nazionale Yasuní, Ecuador',
    country: 'Ecuador',
    lat: -1.0,
    lng: -76.0,
    youtubeSearch: 'Progetto Happiness tribù Waorani Ecuador Yasuní',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/12/Thumbnail-Waorani.jpg',
  },
  {
    id: 76,
    title: 'Dalle baraccopoli alla foresta: i campesinos dell\'Ecuador',
    description: 'E se vi dicessi che i campesinos ecuadoriani stanno salvando il pianeta prendendosi cura dei nostri alberi? Sono andato in Ecuador con Treedom per documentare come un albero possa invertire il trend.',
    location: 'Ecuador',
    country: 'Ecuador',
    lat: -1.8312,
    lng: -78.1834,
    youtubeSearch: 'Progetto Happiness campesinos Ecuador Treedom foresta',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/12/Thumbnail-Ecuador.jpg',
  },
  {
    id: 77,
    title: 'L\'uomo più solo d\'Islanda',
    description: 'L\'Islanda è un paradiso naturale, ma non è semplice viverci. Anzi, è uno dei paesi con la più bassa densità di popolazione al mondo.',
    location: 'Islanda',
    country: 'Islanda',
    lat: 64.9631,
    lng: -19.0208,
    youtubeSearch: 'Progetto Happiness uomo solo Islanda',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/11/Islanda.jpg',
  },
  {
    id: 78,
    title: 'Sopravvivere 72 ore nella foresta',
    description: 'Ho deciso di lasciare a casa il cellulare per immergermi nella natura selvaggia e sopravvivere 3 giorni in una foresta boreale con Valeria Margherita Mosca, etnobotanica e esperta di foraging.',
    location: 'Foresta boreale, Italia',
    country: 'Italia',
    lat: 46.0,
    lng: 11.0,
    youtubeSearch: 'Progetto Happiness sopravvivere foresta 72 ore',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/10/IntoTheWild.jpg',
  },
  {
    id: 79,
    title: 'Il VOODOO: la religione più fraintesa al mondo',
    description: 'Bambole con gli spilli, magia nera, stregoneria. Quando senti la parola voodoo, probabilmente pensi a questo.',
    location: 'Benin',
    country: 'Benin',
    lat: 6.4969,
    lng: 2.6289,
    youtubeSearch: 'Progetto Happiness Voodoo Benin religione',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/09/thumbnail-vodoo.jpg',
  },
  {
    id: 80,
    title: 'La Sposa Bambina: matrimonio a 13 anni',
    description: 'Prova a pensare a una bambina di 13 anni obbligata a sposarsi con un uomo di 50. Una realtà che purtroppo esiste ancora oggi.',
    location: 'Benin',
    country: 'Benin',
    lat: 9.3077,
    lng: 2.3158,
    youtubeSearch: 'Progetto Happiness sposa bambina Benin',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/07/La-Sposa-Bambina-Progetto-Happiness.jpg',
  },
  {
    id: 81,
    title: 'Creare un\'oasi in mezzo alla savana',
    description: 'Il Corno d\'Africa sta vivendo il periodo di siccità più duro di tutta la sua storia. A causa del cambiamento climatico piove così poco che i contadini devono scappare per non morire di fame.',
    location: 'Kenya',
    country: 'Kenya',
    lat: 0.5,
    lng: 37.5,
    youtubeSearch: 'Progetto Happiness oasi savana Kenya siccità',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/06/giuseppe-progetto-happiness-savana.jpg',
  },
  {
    id: 82,
    title: 'Vivere in Kenya con un bambino adottato a distanza',
    description: 'Adottare un bambino è un gesto meraviglioso che ti cambia la vita perché impari ad amare incondizionatamente. Ma come cambia per davvero la vita di quel bambino?',
    location: 'Kenya',
    country: 'Kenya',
    lat: -1.2921,
    lng: 36.8219,
    youtubeSearch: 'Progetto Happiness Kenya adozioni distanza ActionAid',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/05/Cover-Action-Aid.jpg',
  },
  {
    id: 83,
    title: 'Dentro la baraccopoli più grande d\'Africa: Kibera',
    description: 'Perché nel mondo si stanno formando sempre più baraccopoli? Ormai quasi 2 milioni di persone vive in mondi di lamiera senza acqua corrente, luce, bagni in casa.',
    location: 'Kibera, Nairobi, Kenya',
    country: 'Kenya',
    lat: -1.3133,
    lng: 36.7876,
    youtubeSearch: 'Progetto Happiness Kibera Nairobi baraccopoli Africa',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/05/baraccopoli-slum-kibera.jpg',
  },
  {
    id: 84,
    title: 'La rotta migratoria più letale al mondo - Episodio 02',
    description: 'Nel primo episodio ho documentato l\'arrivo sulla nave Ocean Viking e purtroppo un naufragio. In questo secondo episodio riusciamo a salvare 236 rifugiati.',
    location: 'Mar Mediterraneo',
    country: 'Mediterraneo',
    lat: 34.5,
    lng: 14.0,
    youtubeSearch: 'Progetto Happiness rotta migratoria Ocean Viking episodio 2',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/04/Thumbnail-progettohappiness-reportage-migranti-02.jpg',
  },
  {
    id: 85,
    title: 'La rotta migratoria più letale al mondo - Episodio 01',
    description: 'Si parla tanto di migranti e di profughi di guerra. Sappiamo bene da cosa scappano le persone ucraine e possiamo empatizzare attraverso le immagini della guerra.',
    location: 'Mar Mediterraneo',
    country: 'Mediterraneo',
    lat: 35.0,
    lng: 15.0,
    youtubeSearch: 'Progetto Happiness rotta migratoria Ocean Viking episodio 1',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/04/Thumbnail-Ocean-VIking.jpg',
  },
  {
    id: 86,
    title: 'Dietro le quinte del mio primo TEDx',
    description: 'Partecipare a un TEDx era solo un grande sogno prima di iniziare questo Progetto. Alla fine ci sono riuscito.',
    location: 'Bergamo, Italia',
    country: 'Italia',
    lat: 45.6983,
    lng: 9.6773,
    youtubeSearch: 'Progetto Happiness TEDx Bergamo',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/02/TedX-ProgettoHappiness.jpg',
  },
  {
    id: 87,
    title: 'Dentro il Quirinale, la casa degli italiani',
    description: 'Vi siete mai chiesti chi lavora e vive dentro al Quirinale? Ho avuto l\'onore di essere invitato a fare un tour privato del Palazzo più importante d\'Italia.',
    location: 'Roma, Italia',
    country: 'Italia',
    lat: 41.8992,
    lng: 12.4889,
    youtubeSearch: 'Progetto Happiness Quirinale Roma tour',
    views: '',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/02/dentro-il-qurinale-progetto-happiness.jpg',
  },
  {
    id: 88,
    title: 'Terapia d\'urto: a scuola di apnea con Francesco Sena',
    description: 'Ho sempre avuto una paura folle del mare aperto, ma ho deciso di usare una terapia d\'urto: imparare a fare apnea! Il piano è partire con la barca a vela di Francesco Sena.',
    location: 'Italia',
    country: 'Italia',
    lat: 40.5,
    lng: 14.2,
    youtubeSearch: 'Progetto Happiness apnea Francesco Sena',
    views: '',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2021/12/APNEA_Thumbnail_FrancescoSena.jpg',
  },
  {
    id: 89,
    title: 'Perché lo fate? - Speciale Iraq Episodio 03',
    description: 'Ultimo giorno di missione. Dopo essere stato 7 giorni al fianco di medici che dedicano le loro ferie a missioni umanitarie in zone di guerra, voglio capire il perché lo fanno.',
    location: 'Nassiriya, Iraq',
    country: 'Iraq',
    lat: 31.0439,
    lng: 46.2571,
    youtubeSearch: 'Progetto Happiness Iraq speciale episodio 3',
    views: '',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2021/12/cover-missione-iraq-ep-03.jpg',
  },
  {
    id: 90,
    title: 'Incendio in Ospedale - Speciale Iraq Episodio 02',
    description: 'Queste malformazioni vengono viste come punizioni di Dio, e sia i bambini sia le loro famiglie vengono emarginati dalla società. Non si tratta di semplici operazioni, ma dell\'unica opportunità per essere accettati.',
    location: 'Nassiriya, Iraq',
    country: 'Iraq',
    lat: 31.05,
    lng: 46.26,
    youtubeSearch: 'Progetto Happiness Iraq ospedale speciale episodio 2',
    views: '',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2021/12/cover-missione-iraq-ep-02.jpg',
  },
  {
    id: 91,
    title: 'Arrivo a Nassiriya - Speciale Iraq Episodio 01',
    description: 'Sono andato in Iraq, Nassiriya con l\'organizzazione umanitaria Emergenza Sorrisi che opera bambini affetti da malformazioni al viso in zone di guerra. Ho trascorso 1 settimana fianco a fianco dei nostri medici.',
    location: 'Nassiriya, Iraq',
    country: 'Iraq',
    lat: 31.04,
    lng: 46.25,
    youtubeSearch: 'Progetto Happiness Nassiriya Iraq missione Emergenza Sorrisi',
    views: '',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2021/10/thumbnail-iraq.jpg',
  },
  {
    id: 92,
    title: 'La mia felicità: la missione di Fabio Rovazzi',
    description: 'Cosa vuol dire essere felici per Fabio Rovazzi? Ho passato 8 giorni al suo fianco durante le riprese del suo ultimo videoclip musicale.',
    location: 'Italia',
    country: 'Italia',
    lat: 45.4642,
    lng: 9.19,
    youtubeSearch: 'Progetto Happiness Fabio Rovazzi felicità',
    views: '',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2021/07/lamiafelicità-rovazzi.jpg',
  },
  {
    id: 93,
    title: 'Voglio diventare un pilota d\'aerei',
    description: 'Ho avuto l\'onore di essere invitato dall\'Aeronautica Militare per scoprire il loro mondo. Ho visitato la Scuola Militare Aeronautica Douhet dove ho incontrato ragazzi che già a 15 anni hanno le idee chiare.',
    location: 'Guidonia, Italia',
    country: 'Italia',
    lat: 41.9931,
    lng: 12.7231,
    youtubeSearch: 'Progetto Happiness pilota Aeronautica Militare',
    views: '',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2021/04/diventare-pilota-areonautica.jpg',
  },
  {
    id: 94,
    title: 'Il mio Digital Detox: 30 giorni senza Social Media',
    description: 'Avevo bisogno di staccare. Avevo bisogno di capire chi ero senza i social.',
    location: 'Italia',
    country: 'Italia',
    lat: 40.0,
    lng: 12.0,
    youtubeSearch: 'Progetto Happiness digital detox 30 giorni senza social',
    views: '',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2021/03/un-mese-senza-social.jpg',
  },
  {
    id: 95,
    title: 'Visitare Firenze con il suo cantastorie: WikiPedro',
    description: 'L\'arte non è noiosa, bisogna saperla raccontare. Non esiste frase migliore che possa introdurre WikiPedro.',
    location: 'Firenze, Italia',
    country: 'Italia',
    lat: 43.7696,
    lng: 11.2558,
    youtubeSearch: 'Progetto Happiness WikiPedro Firenze',
    views: '',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2021/02/fiorentinità-wikipedro.jpg',
  },
  {
    id: 96,
    title: 'Ristorante Numero Zero Perugia',
    description: 'A Perugia esiste un ristorante dove il 50% del personale viene dai Servizi di Salute Mentale: il Numero Zero. Un esempio di business sociale che ridà dignità e opportunità di lavoro.',
    location: 'Perugia, Italia',
    country: 'Italia',
    lat: 43.1107,
    lng: 12.3908,
    youtubeSearch: 'Progetto Happiness Numero Zero Perugia ristorante',
    views: '',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2021/01/Ristorante-Numero-Zero-Perugia.jpg',
  },
  {
    id: 97,
    title: 'La mia foresta da 1 Milione di alberi salverà il mondo',
    description: 'Se ti dicessi che insieme possiamo creare una foresta tutta nostra?! Ognuno di noi ha la possibilità di regalare un vero albero e scegliere di farlo crescere nel posto del Mondo che preferisce!',
    location: 'Toscana, Italia',
    country: 'Italia',
    lat: 43.7711,
    lng: 11.2486,
    youtubeSearch: 'Progetto Happiness Treedom Federico Garcea foresta',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/12/garcea-treedom-progetto-happiness.jpg',
  },
  {
    id: 98,
    title: 'Valerio Braschi: il più giovane vincitore di Masterchef',
    description: 'Valerio Braschi è uno chef prodigio: a 18 anni ha vinto la sesta edizione di Masterchef e ora punta alla prima stella Michelin. Sono andato a conoscerlo nel suo ristorante a Roma.',
    location: 'Roma, Italia',
    country: 'Italia',
    lat: 41.9028,
    lng: 12.4964,
    youtubeSearch: 'Progetto Happiness Valerio Braschi Masterchef Roma',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/12/valerio-braschi-progetto-happiness.jpg',
  },
  {
    id: 99,
    title: 'Ho incontrato un vero Hobbit: Nicolas Gentile',
    description: 'Nella terra di mezzo italiana, ovvero l\'Abruzzo, vive un vero HOBBIT che sta costruendo una vera contea! Non è un evento Cosplay e nemmeno una festa a tema.',
    location: 'Abruzzo, Italia',
    country: 'Italia',
    lat: 42.35,
    lng: 13.4,
    youtubeSearch: 'Progetto Happiness Nicolas Gentile Hobbit Abruzzo',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/11/nicolas-gentile-hobbit.jpg',
  },
  {
    id: 100,
    title: 'A spasso per Vincent City con Vincent Brunetti',
    description: 'L\'eremo di Vincent, l\'Isola di White, Vincent City. Non esiste un altro posto così nel mondo!',
    location: 'Puglia, Italia',
    country: 'Italia',
    lat: 41.1,
    lng: 16.87,
    youtubeSearch: 'Progetto Happiness Vincent Brunetti Vincent City Puglia',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/11/vincent_brunetti.jpg',
  },
  {
    id: 101,
    title: 'Jago: la mia arte è virale',
    description: 'Jago (Jacopo Cardillo) a 33 anni è considerato uno dei migliori scultori al mondo. Non male per un autodidatta.',
    location: 'Napoli, Italia',
    country: 'Italia',
    lat: 40.8518,
    lng: 14.2681,
    youtubeSearch: 'Progetto Happiness Jago scultore Napoli',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/11/jago-artista.jpg',
  },
  {
    id: 102,
    title: 'Dalla Serie A alla strada: i cugini Schillaci',
    description: 'Il successo che ti regala il calcio non è per sempre. Certe volte la vita te lo toglie.',
    location: 'Palermo, Italia',
    country: 'Italia',
    lat: 38.1157,
    lng: 13.3615,
    youtubeSearch: 'Progetto Happiness Schillaci Serie A Palermo',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/11/cugini-schillaci.jpg',
  },
  {
    id: 103,
    title: 'Giosho Morishita: un monaco giapponese in Sicilia',
    description: '36 anni fa, un Monaco buddista di Osaka ha lasciato tutto per scongiurare la III Guerra Mondiale. Girava il mondo col suo tamburo pregando per la pace, fino a che non è arrivato a Comiso.',
    location: 'Comiso, Sicilia, Italia',
    country: 'Italia',
    lat: 36.9469,
    lng: 14.6036,
    youtubeSearch: 'Progetto Happiness Giosho Morishita monaco giapponese Sicilia',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/10/monaco-giapponese-giappone.jpg',
  },
  {
    id: 104,
    title: 'La mafia uccide, il silenzio pure: la rivoluzione di Addiopizzo',
    description: 'Perché parlare di mafia in un viaggio alla ricerca della felicità? Ragazze e ragazzi con coraggio hanno deciso di dedicare la loro vita per sconfiggerla e proteggere i negozianti.',
    location: 'Palermo, Italia',
    country: 'Italia',
    lat: 38.1157,
    lng: 13.3615,
    youtubeSearch: 'Progetto Happiness Addiopizzo mafia Palermo',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/10/addiopizzo-palermo.jpg',
  },
  {
    id: 105,
    title: 'Roberto Zanda: sono diventato un animale per sopravvivere',
    description: 'Vi è mai capitato di guardare in tv quegli sportivi estremi che portano il proprio corpo al limite? Mi ha sempre incuriosito comprendere che motivazioni potessero avere.',
    location: 'Cagliari, Sardegna, Italia',
    country: 'Italia',
    lat: 39.2238,
    lng: 9.1217,
    youtubeSearch: 'Progetto Happiness Roberto Zanda Cagliari Sardegna',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/09/Roberto-Zanda-Massiccione.jpg',
  },
  {
    id: 106,
    title: 'La felicità per un eremita: Mauro Morandi',
    description: 'Questa è l\'incredibile storia di Mauro Morandi, il guardiano dell\'Isola di Budelli. Per Mauro la domanda se potessi vivere su un\'isola deserta era una domanda molto seria.',
    location: 'Isola di Budelli, Sardegna, Italia',
    country: 'Italia',
    lat: 41.2833,
    lng: 9.35,
    youtubeSearch: 'Progetto Happiness Mauro Morandi Budelli eremita',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/09/intervista-mauro-morandi.jpg',
  },
  {
    id: 107,
    title: 'Intervista con Luca Parmitano: la felicità per un astronauta',
    description: 'Diventare un astronauta è il sogno impossibile per eccellenza. Pochi eletti ci sono riusciti e possono essere considerati dei super umani per le loro capacità.',
    location: 'Houston, USA',
    country: 'USA',
    lat: 29.5502,
    lng: -95.098,
    youtubeSearch: 'Progetto Happiness Luca Parmitano astronauta intervista',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/07/intervista-luca-parmitano.jpg',
  },
  {
    id: 108,
    title: 'Dentro la Stazione Spaziale Internazionale',
    description: 'Cosa mangiano gli astronauti? Si allenano nello spazio? Un viaggio dentro la vita quotidiana sulla Stazione Spaziale Internazionale.',
    location: 'Stazione Spaziale Internazionale',
    country: 'Spazio',
    lat: 29.5502,
    lng: -95.098,
    youtubeSearch: 'Progetto Happiness Stazione Spaziale Internazionale astronauti',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/06/luca-parmitano-spazio.jpg',
  },
  {
    id: 109,
    title: 'Visitare la NASA con un tour privato',
    description: 'È sempre stato uno dei miei sogni da bambino visitare il centro della NASA a Houston. Questa è una di quelle storie che racconterò ai miei figli e ai miei nipoti.',
    location: 'Houston, Texas, USA',
    country: 'USA',
    lat: 29.5502,
    lng: -95.098,
    youtubeSearch: 'Progetto Happiness NASA Houston tour privato',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/06/progetto-happiness-visitare-la-nasa.jpg',
  },
  {
    id: 110,
    title: 'Zion Clark: nato senza gambe, cresciuto senza scuse',
    description: 'Questa è l\'incredibile storia di Zion Clark, un ragazzo nato senza gambe a causa della sindrome regressione caudale, abbandonato dalla madre alla nascita e cresciuto tra case d\'affidamento.',
    location: 'Los Angeles, USA',
    country: 'USA',
    lat: 34.0522,
    lng: -118.2437,
    youtubeSearch: 'Progetto Happiness Zion Clark senza gambe',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/05/zion-clark.jpg',
  },
  {
    id: 111,
    title: 'Sisters of the Valley: le suore della Marijuana',
    description: 'Suore, religione e marijuana: una combinazione particolare. Nel 2020 ci sono ancora poche cose che possono stupirci e io credo che oggi posso raccontarvene almeno una.',
    location: 'Merced, California, USA',
    country: 'USA',
    lat: 37.3022,
    lng: -120.483,
    youtubeSearch: 'Progetto Happiness Sisters of the Valley marijuana California',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/04/sisters-of-the-valley.jpg',
  },
  {
    id: 112,
    title: 'Essere una IDOL in Giappone: la vita di Yuriko Tiger',
    description: 'Sapete cos\'è un IDOL? E una COSPLAYER? L\'autore spiega di non sapere nulla di questi mondi prima di incontrare Eleonora Guglielmi, nota come Yuriko Tiger.',
    location: 'Tokyo, Giappone',
    country: 'Giappone',
    lat: 35.6995,
    lng: 139.7711,
    youtubeSearch: 'Progetto Happiness Yuriko Tiger IDOL Giappone Akihabara',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/03/yuriko-tiger-eleonora-guglielmi.jpg',
  },
  {
    id: 113,
    title: 'Lentil as Anything: il ristorante pay as you feel',
    description: 'In questo episodio vi porto dietro le quinte di un ristorante molto speciale in Australia! Tutti pensavano che fosse completamente matto ma alla fine aveva ragione lui.',
    location: 'Melbourne, Australia',
    country: 'Australia',
    lat: -37.8136,
    lng: 144.9631,
    youtubeSearch: 'Progetto Happiness Lentil as Anything Australia ristorante',
    views: '',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2020/03/lentiasanything-intervista.jpg',
  },
];

// Geography of Happiness — philosophical concepts by country
export const happinessConcepts = [
  { country: 'Norvegia', concept: 'Friluftsliv', meaning: 'Armonia con la natura', lat: 60.472, lng: 8.4689 },
  { country: 'Giappone', concept: 'Kintsugi', meaning: 'Riparare con l\'oro, bellezza nell\'imperfezione', lat: 36.2048, lng: 138.2529 },
  { country: 'Danimarca', concept: 'Hygge', meaning: 'Accettazione e piccole cose', lat: 56.2639, lng: 9.5018 },
  { country: 'Grecia', concept: 'Meraki', meaning: 'Fare le cose con l\'anima', lat: 39.0742, lng: 21.8243 },
  { country: 'Portogallo', concept: 'Saudade', meaning: 'Nostalgia come felicità', lat: 39.3999, lng: -8.2245 },
  { country: 'Corea del Sud', concept: 'Nunchi', meaning: 'Leggere le emozioni degli altri', lat: 35.9078, lng: 127.7669 },
  { country: 'Turchia', concept: 'Sohbet', meaning: 'L\'arte della conversazione profonda', lat: 38.9637, lng: 35.2433 },
  { country: 'Finlandia', concept: 'Sisu', meaning: 'Resilienza e forza interiore', lat: 61.9241, lng: 25.7482 },
  { country: 'Svezia', concept: 'Lagom', meaning: 'Equilibrio, moderazione, armonia', lat: 60.1282, lng: 18.6435 },
  { country: 'India', concept: 'Jugaad', meaning: 'Problem-solving creativo', lat: 20.5937, lng: 78.9629 },
  { country: 'Africa', concept: 'Ubuntu', meaning: 'Benessere collettivo', lat: 0.0, lng: 25.0 },
  { country: 'Hawaii', concept: 'Ho\'oponopono', meaning: 'L\'arte dell\'equilibrio interiore', lat: 19.8968, lng: -155.5828 },
  { country: 'Olanda', concept: 'Niksen', meaning: 'La filosofia del rallentare', lat: 52.1326, lng: 5.2913 },
];
