// Progetto Happiness — Episode & Location Data
// Source: progettohappiness.com + YouTube @ProgettoHappiness

export const PROJECT_INFO = {
  name: 'Progetto Happiness',
  founder: 'Giuseppe Bertuccio D\'Angelo',
  founded: 2019,
  description: 'Un viaggio alla ricerca delle infinite sfumature della felicità attraverso culture, popoli e filosofie di vita.',
  stats: {
    subscribers: '2.7M',
    followers: '503K',
    episodes: '900+',
    countries: '50+',
  },
};

// Each episode with geocoordinates for globe placement
export const episodes = [
  {
    id: 1,
    title: 'BDSM: dentro il mondo segreto del piacere',
    description: 'Cosa spinge un manager di successo a pagare per farsi umiliare? Un viaggio nel mondo sommerso del BDSM a San Francisco.',
    location: 'San Francisco, USA',
    country: 'USA',
    lat: 37.7749,
    lng: -122.4194,
    youtubeSearch: 'Progetto Happiness BDSM San Francisco',
    views: '4.2M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2026/03/SlaveMen.jpg',
  },
  {
    id: 2,
    title: 'I soldi fanno la felicità?',
    description: 'Paracelsus Recovery a Zurigo è la clinica di salute mentale più esclusiva del pianeta. I soldi possono davvero comprare la felicità?',
    location: 'Zurigo, Svizzera',
    country: 'Svizzera',
    lat: 47.3769,
    lng: 8.5417,
    youtubeSearch: 'Progetto Happiness soldi felicità Zurigo',
    views: '2.8M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2026/02/paracelsius-recovery-cover.jpg',
  },
  {
    id: 3,
    title: 'Riserva di Pine Ridge',
    description: 'La felicità nel luogo più povero degli Stati Uniti. La riserva indiana di Pine Ridge, tra i Lakota.',
    location: 'South Dakota, USA',
    country: 'USA',
    lat: 43.0,
    lng: -102.5,
    youtubeSearch: 'Progetto Happiness Pine Ridge Lakota',
    views: '3.1M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2026/02/Pine-Ridge-2.jpg',
  },
  {
    id: 4,
    title: 'Gold\'s Gym Venice',
    description: 'La Mecca del bodybuilding dove si è allenato Arnold Schwarzenegger. Cosa significa inseguire il corpo perfetto?',
    location: 'Venice, California',
    country: 'USA',
    lat: 33.985,
    lng: -118.472,
    youtubeSearch: 'Progetto Happiness Gold Gym Venice',
    views: '1.9M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2026/02/Bodybuilders.jpg',
  },
  {
    id: 5,
    title: 'Preppers: pronti alla fine del mondo',
    description: 'Persone che si preparano alla fine del mondo. Bunker, scorte e sopravvivenza negli Stati Uniti.',
    location: 'USA',
    country: 'USA',
    lat: 39.8283,
    lng: -98.5795,
    youtubeSearch: 'Progetto Happiness Preppers bunker',
    views: '2.5M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2026/01/Preppers-Cover.jpg',
  },
  {
    id: 6,
    title: 'La vita degli ultimi cowboy',
    description: 'La vita degli ultimi cowboy nel Far West americano. Montana, cavalli e libertà.',
    location: 'Montana, USA',
    country: 'USA',
    lat: 46.8797,
    lng: -110.3626,
    youtubeSearch: 'Progetto Happiness cowboy Montana',
    views: '2.1M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2026/01/Cowboy-Cover.jpg',
  },
  {
    id: 7,
    title: 'Orania: la città più razzista al mondo',
    description: 'La città più razzista al mondo. Un enclave afrikaner nel cuore del Sudafrica.',
    location: 'Orania, Sudafrica',
    country: 'Sudafrica',
    lat: -29.818,
    lng: 24.615,
    youtubeSearch: 'Progetto Happiness Orania Sudafrica',
    views: '5.1M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/11/Orania.jpg',
  },
  {
    id: 8,
    title: 'Cape Town: vivere o morire',
    description: 'La città più pericolosa al mondo. Cape Town tra bellezza estrema e violenza quotidiana.',
    location: 'Cape Town, Sudafrica',
    country: 'Sudafrica',
    lat: -33.9249,
    lng: 18.4241,
    youtubeSearch: 'Progetto Happiness Cape Town pericolosa',
    views: '3.7M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/11/Khaytelitsha.jpg',
  },
  {
    id: 9,
    title: 'Black Mambas',
    description: 'Sopravvivere disarmati tra gli animali feroci. Le Black Mambas, ranger anti-bracconaggio nel Kruger National Park.',
    location: 'Kruger Park, Sudafrica',
    country: 'Sudafrica',
    lat: -23.9884,
    lng: 31.5547,
    youtubeSearch: 'Progetto Happiness Black Mambas Kruger',
    views: '1.8M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/11/sopravvivere-animali-africa.jpg',
  },
  {
    id: 10,
    title: 'Come cambiare la vita a 300 bambini',
    description: 'Costruire una scuola in Zimbabwe. Il Progetto Scuola che ha cambiato la vita a 300 bambini.',
    location: 'Kapale, Zimbabwe',
    country: 'Zimbabwe',
    lat: -19.0,
    lng: 29.0,
    youtubeSearch: 'Progetto Happiness scuola Zimbabwe',
    views: '2.3M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/09/THUMB-ZIMBABWE-3.jpg',
  },
  {
    id: 11,
    title: '48h con i Monaci Buddhisti',
    description: 'I monaci che custodiscono il segreto della felicità. 48 ore nel cuore spirituale di Luang Prabang.',
    location: 'Luang Prabang, Laos',
    country: 'Laos',
    lat: 19.8856,
    lng: 102.1347,
    youtubeSearch: 'Progetto Happiness monaci buddhisti Laos',
    views: '4.5M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/09/THUMB-2.jpg',
  },
  {
    id: 12,
    title: 'Muay Thai: la lotta più dura al mondo',
    description: 'La Muay Thai in Tailandia. Bambini che combattono per sopravvivere.',
    location: 'Tailandia',
    country: 'Tailandia',
    lat: 13.7563,
    lng: 100.5018,
    youtubeSearch: 'Progetto Happiness Muay Thai Tailandia',
    views: '3.2M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/09/MuayThai1.jpg',
  },
  {
    id: 13,
    title: 'Gli uomini elefante',
    description: 'La tribù dei Mahout che vive con gli elefanti. Un legame millenario in Tailandia.',
    location: 'Tailandia',
    country: 'Tailandia',
    lat: 18.7883,
    lng: 98.9853,
    youtubeSearch: 'Progetto Happiness Mahout elefanti Tailandia',
    views: '2.0M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/08/THUMB-ELEPHANTS-3.jpg',
  },
  {
    id: 14,
    title: 'Laamb: i gladiatori d\'Africa',
    description: 'Diventare il più grande gladiatore d\'Africa. La lotta Laamb a Dakar, Senegal.',
    location: 'Dakar, Senegal',
    country: 'Senegal',
    lat: 14.7167,
    lng: -17.4677,
    youtubeSearch: 'Progetto Happiness Laamb Dakar Senegal',
    views: '2.6M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/07/Laamb.jpg',
  },
  {
    id: 15,
    title: 'Miniere illegali di smeraldi',
    description: 'Dentro le miniere illegali di smeraldi in Colombia. Rischio, povertà e speranza.',
    location: 'Boyacá, Colombia',
    country: 'Colombia',
    lat: 5.4545,
    lng: -73.362,
    youtubeSearch: 'Progetto Happiness miniere smeraldi Colombia',
    views: '3.8M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/07/miniere-smeraldi-colombia.jpg',
  },
  {
    id: 16,
    title: 'Il più grande cimitero elettronico',
    description: 'Dentro il più grande cimitero elettronico del pianeta. Agbogbloshie, Ghana.',
    location: 'Agbogbloshie, Ghana',
    country: 'Ghana',
    lat: 5.5527,
    lng: -0.2342,
    youtubeSearch: 'Progetto Happiness Agbogbloshie Ghana',
    views: '2.9M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/07/discarica-Ghana.jpg',
  },
  {
    id: 17,
    title: 'Le tribù urbane di New York',
    description: 'Chi sono i veri americani? Le tribù urbane di New York City.',
    location: 'New York, USA',
    country: 'USA',
    lat: 40.7128,
    lng: -74.006,
    youtubeSearch: 'Progetto Happiness tribù urbane New York',
    views: '1.7M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/07/urban-tribes.jpg',
  },
  {
    id: 18,
    title: 'Diventare un uomo invisibile',
    description: 'La vita di un senzatetto a New York. Diventare un uomo invisibile nella città che non dorme mai.',
    location: 'New York, USA',
    country: 'USA',
    lat: 40.7580,
    lng: -73.9855,
    youtubeSearch: 'Progetto Happiness senzatetto New York',
    views: '3.4M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/07/Homeless.jpg',
  },
  {
    id: 19,
    title: 'Una notte con i banditi di Bogotá',
    description: 'Una notte con i banditi di Bogotá. Il lato oscuro della capitale colombiana.',
    location: 'Bogotá, Colombia',
    country: 'Colombia',
    lat: 4.711,
    lng: -74.0721,
    youtubeSearch: 'Progetto Happiness banditi Bogotá',
    views: '4.1M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/05/Banditi-Bogota.jpg',
  },
  {
    id: 20,
    title: 'Il popolo che salverà il mondo',
    description: 'La tribù Kogui nella selva colombiana. Il popolo che crede di poter salvare il mondo.',
    location: 'Sierra Nevada, Colombia',
    country: 'Colombia',
    lat: 10.8,
    lng: -73.7,
    youtubeSearch: 'Progetto Happiness Kogui Colombia',
    views: '2.7M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/04/Kogui-Tribe-1.jpg',
  },
  {
    id: 21,
    title: 'L\'isola più affollata del mondo',
    description: 'Come sopravvivere in 1.000 su un\'isola grande quanto un campo da calcio? Santa Cruz del Islote.',
    location: 'Santa Cruz del Islote, Colombia',
    country: 'Colombia',
    lat: 9.685,
    lng: -75.883,
    youtubeSearch: 'Progetto Happiness Santa Cruz Islote',
    views: '5.3M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/04/Isola-di-Santa-Cruz.jpg',
  },
  {
    id: 22,
    title: 'Rastafarianesimo in Giamaica',
    description: 'La religione che venera la pianta della conoscenza. Il rastafarianesimo in Giamaica.',
    location: 'Giamaica',
    country: 'Giamaica',
    lat: 18.1096,
    lng: -77.2975,
    youtubeSearch: 'Progetto Happiness Rastafarianesimo Giamaica',
    views: '2.2M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/03/Rastamen1.jpg',
  },
  {
    id: 23,
    title: 'Guerrieri Kara: l\'arte della sopravvivenza',
    description: 'L\'arte della sopravvivenza nella Valle dell\'Omo, Etiopia. I guerrieri della tribù Kara.',
    location: 'Valle dell\'Omo, Etiopia',
    country: 'Etiopia',
    lat: 5.5,
    lng: 36.0,
    youtubeSearch: 'Progetto Happiness guerrieri Kara Etiopia',
    views: '1.5M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/03/Kara.jpg',
  },
  {
    id: 24,
    title: 'Il rito delle donne frustate',
    description: 'Il rito delle donne frustate nella tribù degli Hamer. Valle dell\'Omo, Etiopia.',
    location: 'Valle dell\'Omo, Etiopia',
    country: 'Etiopia',
    lat: 5.3,
    lng: 36.5,
    youtubeSearch: 'Progetto Happiness Hamer Etiopia',
    views: '2.4M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/03/Hamer.jpg',
  },
  {
    id: 25,
    title: 'Gli ultimi uomini della pietra',
    description: 'Sopravvivere nella savana con gli Hadzabe. Gli ultimi cacciatori-raccoglitori della Tanzania.',
    location: 'Tanzania',
    country: 'Tanzania',
    lat: -3.3869,
    lng: 36.6,
    youtubeSearch: 'Progetto Happiness Hadzabe Tanzania',
    views: '3.6M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2025/03/Hadzabe-Primitive-Hunters.jpg',
  },
  {
    id: 26,
    title: 'La tribù della felicità',
    description: 'I Chewa: la tribù della felicità in Malawi. Un popolo che celebra la vita attraverso la danza.',
    location: 'Malawi',
    country: 'Malawi',
    lat: -13.2543,
    lng: 34.3015,
    youtubeSearch: 'Progetto Happiness Chewa Malawi',
    views: '1.9M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/12/thumb1.jpg',
  },
  {
    id: 27,
    title: 'L\'isola segreta degli albini',
    description: 'L\'isola segreta degli albini africani nel Lago Vittoria, Tanzania.',
    location: 'Lago Vittoria, Tanzania',
    country: 'Tanzania',
    lat: -1.0,
    lng: 33.0,
    youtubeSearch: 'Progetto Happiness albini Tanzania',
    views: '2.8M',
    date: '2021',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/11/Albinos-Tanzania.jpeg',
  },
  {
    id: 28,
    title: 'I cacciatori con le aquile',
    description: 'I cacciatori con le aquile della Mongolia. Una tradizione millenaria nelle steppe gelate.',
    location: 'Mongolia',
    country: 'Mongolia',
    lat: 48.0,
    lng: 89.0,
    youtubeSearch: 'Progetto Happiness cacciatori aquile Mongolia',
    views: '3.3M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/11/Thumb-3.jpg',
  },
  {
    id: 29,
    title: 'Il lavoro più duro al mondo',
    description: 'Gli uomini fogna dell\'India. Il lavoro più duro e pericoloso al mondo.',
    location: 'India',
    country: 'India',
    lat: 28.6139,
    lng: 77.209,
    youtubeSearch: 'Progetto Happiness uomini fogna India',
    views: '4.7M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/10/Manual-thumb-1.jpg',
  },
  {
    id: 30,
    title: 'L\'ultimo matriarcato contro i Talebani',
    description: 'I Kalash: l\'ultimo matriarcato che combatte i Talebani nel cuore del Pakistan.',
    location: 'Chitral, Pakistan',
    country: 'Pakistan',
    lat: 35.7,
    lng: 71.5,
    youtubeSearch: 'Progetto Happiness Kalash Pakistan',
    views: '3.9M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/10/Kalash-thumb-1.jpg',
  },
  {
    id: 31,
    title: 'I bambini minatori della Sierra Leone',
    description: 'I diamanti sporchi. I bambini minatori delle miniere di diamanti della Sierra Leone.',
    location: 'Sierra Leone',
    country: 'Sierra Leone',
    lat: 8.4606,
    lng: -11.7799,
    youtubeSearch: 'Progetto Happiness diamanti Sierra Leone',
    views: '2.1M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/09/Blood-Diamonds-Cover-YouTube.jpg',
  },
  {
    id: 32,
    title: 'Le strade più pericolose al mondo',
    description: 'I camionisti del Pakistan sulle strade più pericolose al mondo. Karakoram Highway.',
    location: 'Karakoram, Pakistan',
    country: 'Pakistan',
    lat: 36.3,
    lng: 75.5,
    youtubeSearch: 'Progetto Happiness camionisti Pakistan Karakoram',
    views: '2.5M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/09/ThumB-4.jpg',
  },
  {
    id: 33,
    title: 'Monte Athos: dove le donne non entrano',
    description: 'L\'unica nazione dove le donne non possono entrare. Monte Athos, Grecia.',
    location: 'Monte Athos, Grecia',
    country: 'Grecia',
    lat: 40.1564,
    lng: 24.3284,
    youtubeSearch: 'Progetto Happiness Monte Athos Grecia',
    views: '4.0M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/09/Athos.jpg',
  },
  {
    id: 34,
    title: 'Monaci Shaolin',
    description: 'Dentro il tempio dei monaci Shaolin. Disciplina, kung fu e spiritualità in Cina.',
    location: 'Henan, Cina',
    country: 'Cina',
    lat: 34.5,
    lng: 112.9,
    youtubeSearch: 'Progetto Happiness Shaolin Cina',
    views: '3.5M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/07/KF8b.jpg',
  },
  {
    id: 35,
    title: 'La prima comunità trans musulmana',
    description: 'La prima comunità trans musulmana in Bangladesh. Dhaka, tra fede e identità.',
    location: 'Dhaka, Bangladesh',
    country: 'Bangladesh',
    lat: 23.8103,
    lng: 90.4125,
    youtubeSearch: 'Progetto Happiness trans musulmana Bangladesh',
    views: '2.6M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/06/Thumb2.jpg',
  },
  {
    id: 36,
    title: 'Fast Fashion: i bambini operai',
    description: 'La storia dei bambini operai nel Fast Fashion. Bangladesh, il prezzo dei vestiti che indossiamo.',
    location: 'Bangladesh',
    country: 'Bangladesh',
    lat: 23.685,
    lng: 90.356,
    youtubeSearch: 'Progetto Happiness fast fashion Bangladesh',
    views: '3.0M',
    date: '2020',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/06/ff2.jpg',
  },
  {
    id: 37,
    title: 'La tribù che sopravvive a -50°',
    description: 'Gli uomini renna della Mongolia. La tribù Tsaatan che sopravvive a -50° tra orsi e lupi.',
    location: 'Mongolia',
    country: 'Mongolia',
    lat: 51.1,
    lng: 99.0,
    youtubeSearch: 'Progetto Happiness uomini renna Mongolia Tsaatan',
    views: '4.3M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/05/Renne2.jpg',
  },
  {
    id: 38,
    title: 'Terre sacre degli sciamani',
    description: 'Viaggio alla scoperta delle terre sacre degli sciamani in Mongolia.',
    location: 'Mongolia',
    country: 'Mongolia',
    lat: 47.9,
    lng: 106.9,
    youtubeSearch: 'Progetto Happiness sciamani Mongolia',
    views: '2.4M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/05/Thumb-6.jpg',
  },
  {
    id: 39,
    title: 'La città segreta nel cimitero',
    description: 'Vivere nelle tombe. La città segreta nel cimitero di Manila, Filippine.',
    location: 'Manila, Filippine',
    country: 'Filippine',
    lat: 14.5995,
    lng: 120.9842,
    youtubeSearch: 'Progetto Happiness cimitero Manila Filippine',
    views: '3.7M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/05/Thumb-1.jpg',
  },
  {
    id: 40,
    title: 'La prigione autogestita dalle gang',
    description: 'Dentro la prigione autogestita dalle gang a Manila.',
    location: 'Manila, Filippine',
    country: 'Filippine',
    lat: 14.58,
    lng: 121.0,
    youtubeSearch: 'Progetto Happiness prigione gang Manila',
    views: '4.8M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/04/Thumb4.jpg',
  },
  {
    id: 41,
    title: 'Uomini pesce Badjao',
    description: 'Mutati geneticamente per sopravvivere in mare. I Badjao delle Filippine.',
    location: 'Filippine',
    country: 'Filippine',
    lat: 6.0,
    lng: 121.0,
    youtubeSearch: 'Progetto Happiness Badjao Filippine',
    views: '2.9M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/04/3.jpg',
  },
  {
    id: 42,
    title: 'Cucinare la spazzatura per sopravvivere',
    description: 'Pag Pag: cucinare la spazzatura per sopravvivere a Manila.',
    location: 'Manila, Filippine',
    country: 'Filippine',
    lat: 14.62,
    lng: 120.97,
    youtubeSearch: 'Progetto Happiness Pag Pag Manila',
    views: '3.1M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/04/PagPag1.jpg',
  },
  {
    id: 43,
    title: 'Canoni di bellezza in Mauritania',
    description: 'Le donne obese della Mauritania. Canoni estetici della bellezza femminile.',
    location: 'Mauritania',
    country: 'Mauritania',
    lat: 18.0735,
    lng: -15.9582,
    youtubeSearch: 'Progetto Happiness donne obese Mauritania',
    views: '2.3M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/03/Fat-Women.jpg',
  },
  {
    id: 44,
    title: 'La febbre dell\'oro africano',
    description: 'La febbre dell\'oro nella Mauritania. Minatori alla ricerca della fortuna nel deserto.',
    location: 'Mauritania',
    country: 'Mauritania',
    lat: 20.0,
    lng: -12.0,
    youtubeSearch: 'Progetto Happiness febbre oro Mauritania',
    views: '1.8M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/03/Thumb1.jpg',
  },
  {
    id: 45,
    title: 'Il villaggio senza occhi',
    description: 'Dali Koumbè: il villaggio della tribù senza occhi nel deserto del Sahara.',
    location: 'Sahara, Mauritania',
    country: 'Mauritania',
    lat: 17.0,
    lng: -10.0,
    youtubeSearch: 'Progetto Happiness villaggio senza occhi Mauritania',
    views: '3.5M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/02/Thumb-4.jpg',
  },
  {
    id: 46,
    title: 'Il treno del ferro',
    description: 'Viaggio clandestino sul treno del ferro in Mauritania. Il treno più lungo e pericoloso al mondo.',
    location: 'Mauritania',
    country: 'Mauritania',
    lat: 21.3,
    lng: -13.0,
    youtubeSearch: 'Progetto Happiness treno ferro Mauritania',
    views: '5.7M',
    date: '2019',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/01/TrenoScrittaSotto.jpg',
  },
  {
    id: 47,
    title: 'Una fidanzata in affitto a Tokyo',
    description: 'Una fidanzata in affitto a Tokyo. Il business della solitudine in Giappone.',
    location: 'Tokyo, Giappone',
    country: 'Giappone',
    lat: 35.6762,
    lng: 139.6503,
    youtubeSearch: 'Progetto Happiness fidanzata affitto Tokyo',
    views: '6.2M',
    date: '2023',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2024/01/Thumb-2.jpg',
  },
  {
    id: 48,
    title: 'Ocean Viking: salvataggio nel Mediterraneo',
    description: 'Il primo content creator a bordo della Ocean Viking. Missione di salvataggio nel Mar Mediterraneo.',
    location: 'Mar Mediterraneo',
    country: 'Mediterraneo',
    lat: 35.0,
    lng: 15.0,
    youtubeSearch: 'Progetto Happiness Ocean Viking Mediterraneo',
    views: '1.6M',
    date: '2022',
    thumb: 'https://progettohappiness.com/wp-content/uploads/2022/04/Thumbnail-Ocean-VIking.jpg',
  },
];

// Geography of Happiness — philosophical concepts by country
export const happinessConcepts = [
  { country: 'Norvegia', concept: 'Friluftsliv', meaning: 'Armonia con la natura', lat: 60.472, lng: 8.4689 },
  { country: 'Giappone', concept: 'Kintsugi', meaning: 'Riparare con l\'oro, bellezza nell\'imperfezione', lat: 36.2048, lng: 138.2529 },
  { country: 'Danimarca', concept: 'Hygge', meaning: 'Accettazione e piccole cose', lat: 56.2639, lng: 9.5018 },
  { country: 'Grecia', concept: 'Meraki', meaning: 'Fare le cose con l\'anima', lat: 39.0742, lng: 21.8243 },
  { country: 'Portogallo', concept: 'Saudade', meaning: 'Nostalgia come felicità', lat: 39.3999, lng: -8.2245 },
  { country: 'Corea del Sud', concept: 'Nunchi', meaning: 'Leggere le emozioni degli altri', lat: 35.9078, lng: 127.7669 },
  { country: 'Turchia', concept: 'Sohbet', meaning: 'L\'arte della conversazione profonda', lat: 38.9637, lng: 35.2433 },
  { country: 'Finlandia', concept: 'Sisu', meaning: 'Resilienza e forza interiore', lat: 61.9241, lng: 25.7482 },
  { country: 'Svezia', concept: 'Lagom', meaning: 'Equilibrio, moderazione, armonia', lat: 60.1282, lng: 18.6435 },
  { country: 'India', concept: 'Jugaad', meaning: 'Problem-solving creativo', lat: 20.5937, lng: 78.9629 },
  { country: 'Africa', concept: 'Ubuntu', meaning: 'Benessere collettivo', lat: 0.0, lng: 25.0 },
  { country: 'Hawaii', concept: 'Ho\'oponopono', meaning: 'L\'arte dell\'equilibrio interiore', lat: 19.8968, lng: -155.5828 },
  { country: 'Olanda', concept: 'Niksen', meaning: 'La filosofia del rallentare', lat: 52.1326, lng: 5.2913 },
];
