// Regenerates `src/teach/library.js` from the Metalab Webkit preset file.
//
//   npm run library
//
// The webkit presets are authored full-screen against the Metalab case media
// on black. Three things are page decisions rather than preset decisions, so
// they are baked onto every entry here:
//
//   images.source  → the teacher portraits this page runs on
//   look.solidBg   → off; the page is paper, not #0c0c0c
//   camera.fit     → the framing correction (see tower.js), with `fitAspect`
//                    set to the ~16:9 canvas they were all authored on
//
// `region` is deliberately NOT baked in: it is where the composition sits on
// THIS page, so flipping through the library must not move it.
//
// Everything else is verbatim. Re-export from the webkit panel, drop the new
// cylinder.json in place, run this, and the shelf picks the new ones up.

import fs from "node:fs";
import path from "node:path";

const HERE = import.meta.dirname;
const ROOT = path.resolve(HERE, "..");
const SRC =
  process.env.PRESETS ||
  path.resolve(ROOT, "../design-component-library/.presets/cylinder.json");
const OUT = path.resolve(ROOT, "src/teach/library.js");

// The two presets whose look depends on page scroll, which this page does not
// have — they still load, they just read as their non-scroll sibling.
const NEEDS_SCROLL = /\(scroll/i;

const slugify = (s) =>
  s
    .toLowerCase()
    .replace(/[()]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const deep = (base, over) => {
  const out = Array.isArray(base) ? base.slice() : { ...base };
  for (const k of Object.keys(over || {})) {
    const b = out[k];
    const o = over[k];
    out[k] =
      b && o && typeof b === "object" && typeof o === "object" && !Array.isArray(o)
        ? deep(b, o)
        : o;
  }
  return out;
};

const PAGE_OVERRIDES = {
  images: { source: "photos", count: 18, video: false },
  camera: { fit: 0.88, fitAspect: 1.62 },
  look: { solidBg: false },
};

if (!fs.existsSync(SRC)) {
  console.error(`No preset file at ${SRC}\nSet PRESETS=/path/to/cylinder.json`);
  process.exit(1);
}

const presets = JSON.parse(fs.readFileSync(SRC, "utf8"));
if (!Array.isArray(presets) || !presets.length) {
  console.error("That file holds no presets.");
  process.exit(1);
}

const entries = presets.map((p) => ({
  name: p.name,
  slug: slugify(p.name),
  shape: p.config?.layout?.shape || "cylinder",
  note: NEEDS_SCROLL.test(p.name)
    ? "authored around page scroll, which this page does not have"
    : null,
  config: deep(p.config, PAGE_OVERRIDES),
}));

const body = entries
  .map(
    (e) =>
      `  {\n    name: ${JSON.stringify(e.name)},\n    slug: ${JSON.stringify(e.slug)},\n` +
      `    shape: ${JSON.stringify(e.shape)},\n    note: ${JSON.stringify(e.note)},\n` +
      `    config: ${JSON.stringify(e.config, null, 6).replace(/\n/g, "\n    ")},\n  },`
  )
  .join("\n");

const file = `// GENERATED by scripts/build-library.mjs — do not hand-edit.
//
// The whole Metalab Webkit cylinder preset library
// (github.com/enricodeia/metalab-webkit → .presets/cylinder.json), verbatim
// apart from three page decisions baked onto every entry: the teacher
// portraits as the image source, a transparent background instead of the
// preset's #0c0c0c, and the \`camera.fit\` framing correction. \`region\` is
// left out on purpose — it is where the composition sits on THIS page, so
// flipping through the library must not move it.
//
// Regenerate with \`npm run library\` after re-exporting from the webkit panel.

export const LIBRARY = [
${body}
];

export const byShape = () => {
  const out = new Map();
  for (const e of LIBRARY) {
    if (!out.has(e.shape)) out.set(e.shape, []);
    out.get(e.shape).push(e);
  }
  return out;
};
`;

fs.writeFileSync(OUT, file);
const shapes = [...new Set(entries.map((e) => e.shape))];
console.log(`${entries.length} presets → src/teach/library.js`);
console.log(`shapes: ${shapes.join(", ")}`);
for (const e of entries) console.log(`  ${e.shape.padEnd(9)} ${e.name}${e.note ? "  ⚠" : ""}`);
